name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      # install Eigen using Homebrew as we need >= v3.4 with CMake targets
      # install pybind11 using Homebrew so that CMake targets are present
      run: |
        brew install eigen pybind11
        pip install .
    - name: Tests
      run: |
        pip install numpy --only-binary=numpy
        cd tests
        python test_regularisation.py
        python test_alternating.py
        python test_multistart.py
        python test_multistart_ls.py
